<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="bom" nsURI="http://example.org/bom" nsPrefix="bom">
  <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
    <details key="documentation" value="Meta Model of Bill of Materials&#xA;&#xA;Parameter Definition Consistency:&#xA;&#xA;Every `ParameterValue` of an `Item` should reference a `ParameterDefinition` belonging to the `ItemType` referenced by that item.&#xA;&#xA;Parameter Value Type Consistency:&#xA;&#xA;The concrete type of a `ParameterValue` should match the `DataType` of its referenced `ParameterDefinition`.&#xA;"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="BOM">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Root element of the Bill of Materials model.&#xA;&#xA;Represents a complete BOM consisting of multiple concrete items."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Name of the BOM."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="items" upperBound="-1"
        eType="#//Item" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Items contained in this BOM.&#xA;&#xA;Each item represents a concrete component or part occurrence and references an `ItemType` that defines its available parameters."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Item">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Concrete item contained in a BOM.&#xA;&#xA;An item represents one specific component or part occurrence. Its structure is defined by an associated `ItemType`, while its actual parameter values are stored locally on the item."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Unique identifier of the item.&#xA;&#xA;The attribute is used as the Ecore ID of the item."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//ItemType">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Item type that defines the parameter schema of this item.&#xA;&#xA;All parameter values assigned to the item are expected to reference parameter definitions belonging to this item type.&#xA;"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameterValues" upperBound="-1"
        eType="#//ParameterValue" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Parameter values assigned to this item.&#xA;&#xA;Each value references a corresponding `ParameterDefinition` and stores the actual value for this concrete item."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numberOfItems" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Number of occurrences represented by this item.&#xA;&#xA;Can be used to express quantities within the BOM without creating multiple identical item instances."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ItemType">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Definition of a specific type of BOM item.&#xA;&#xA;An item type describes the common structure shared by all items of that type."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Name of the item type."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Textual description of the item type.&#xA;&#xA;Provides additional semantic context and documentation for the represented component type."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameterDefinitions" lowerBound="1"
        upperBound="-1" eType="#//ParameterDefinition" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Parameter definitions belonging to this item type.&#xA;&#xA;Defines which parameters are available for all items referencing this type."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ParameterDefinition">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Definition of a parameter belonging to an `ItemType`.&#xA;&#xA;Specifies the semantic name and expected datatype of a parameter.&#xA;&#xA;The actual value is not stored in the parameter definition, but in a corresponding `ParameterValue` attached to an `Item`."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Name of the parameter.&#xA;"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dataType" lowerBound="1"
        eType="#//DataType">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Expected datatype of the parameter value.&#xA;&#xA;Determines which concrete `ParameterValue` specialization should be used for the parameter."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ParameterValue" abstract="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Abstract base class for all parameter values.&#xA;&#xA;Represents the concrete value of a parameter for one specific `Item`.&#xA;&#xA;A parameter value references the `ParameterDefinition` that describes its semantic meaning and expected datatype."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="definition" lowerBound="1"
        eType="#//ParameterDefinition">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Parameter definition associated with this value.&#xA;&#xA;The referenced definition is expected to belong to the `ItemType` referenced by the containing `Item`."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Optional textual description of the concrete parameter value.&#xA;&#xA;Provides additional context when required."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DataType">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Set of supported parameter datatypes.&#xA;&#xA;Defines the expected type of a `ParameterDefinition` and determines which concrete `ParameterValue` class should be used.&#xA;&#xA;The expected mapping is:&#xA;&#xA;EString  -> StringParameterValue &#xA;EDouble  -> DoubleParameterValue &#xA;EBoolean -> BoolParameterValue &#xA;EInt     -> IntegerParameterValue"/>
    </eAnnotations>
    <eLiterals name="EString" literal="EString"/>
    <eLiterals name="EDouble" value="1" literal="DOUBLE"/>
    <eLiterals name="EBoolean" value="2"/>
    <eLiterals name="EInt" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StringParameterValue" eSuperTypes="#//ParameterValue">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Textual parameter value.&#xA;&#xA;Used for descriptive or categorical values such as material names, manufacturer names, or configuration labels."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Textual value of the parameter."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NumericParameterValue" abstract="true"
      eSuperTypes="#//ParameterValue">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Abstract base class for numeric parameter values.&#xA;&#xA;Groups parameter values that represent numerical quantities while allowing integer and doublet values to remain explicitly typed."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BoolParameterValue" eSuperTypes="#//ParameterValue">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Boolean parameter value.&#xA;&#xA;Used for binary properties or configuration states.&#xA;"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Boolean value of the parameter."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DoubleParameterValue" eSuperTypes="#//NumericParameterValue">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Double numeric parameter value.&#xA;&#xA;Used for measurable quantities that can contain fractional values"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Double value of the parameter.&#xA;"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IntegerParameterValue" eSuperTypes="#//NumericParameterValue">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Integer numeric parameter value.&#xA;&#xA;Used for discrete quantities and counts where fractional values are not valid.&#xA;"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Integer value of the parameter.&#xA;"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
