<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="uncertainty" nsURI="http://www.example.org/uncertainty" nsPrefix="uncertainty">
  <eClassifiers xsi:type="ecore:EClass" name="UncertaintyAnnotationRepository">
    <eStructuralFeatures xsi:type="ecore:EReference" name="uncertainties" upperBound="-1"
        eType="#//Uncertainty" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Uncertainty">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" eType="#//UncertaintyKind"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="reducability" eType="#//ReducabilityLevel"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nature" eType="#//UncertaintyNature"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="uncertaintyLocation" eType="#//UncertaintyLocation"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="setManually" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="DefaultID"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="effect" eType="#//Effect"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="onDelete" eType="#//OnDeleteMode"
        defaultValueLiteral="CASCADE"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pattern" eType="#//Pattern"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="perspective" eType="#//UncertaintyPerspective"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="#//UncertaintySource"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="UncertaintyKind">
    <eLiterals name="BeliefUncertainty" value="1"/>
    <eLiterals name="OccurenceUncertainty" value="2"/>
    <eLiterals name="Spatiotemporal" value="3"/>
    <eLiterals name="BehaviorUncertainty" value="4"/>
    <eLiterals name="MeasurementUncertainty" value="5"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ReducabilityLevel">
    <eLiterals name="FullyReducable" value="1"/>
    <eLiterals name="PartiallyReducible" value="2"/>
    <eLiterals name="Irreducible" value="3"/>
    <eLiterals name="Unknown" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="UncertaintyNature">
    <eLiterals name="Aleatory" value="1"/>
    <eLiterals name="Epistemic" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="UncertaintyLocationType">
    <eLiterals name="Parameter"/>
    <eLiterals name="Outcome"/>
    <eLiterals name="Inputs"/>
    <eLiterals name="Analysis"/>
    <eLiterals name="Context"/>
    <eLiterals name="DecisionMaking"/>
    <eLiterals name="ModelInputUncertainty"/>
    <eLiterals name="ModelStructureUncertainty"/>
    <eLiterals name="ModelOutcomeUncertainty"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UncertaintyLocation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="referencedComponents" upperBound="-1"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="location" eType="#//UncertaintyLocationType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="specification" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Effect">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="specification" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="representation" eType="#//StructuralEffectTypeRepresentation"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="stochasticity" eType="#//StochasticityEffectType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="OnDeleteMode">
    <eLiterals name="NO_ACTION"/>
    <eLiterals name="CASCADE" value="1"/>
    <eLiterals name="RESTRICT" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="StructuralEffectTypeRepresentation">
    <eLiterals name="Continous"/>
    <eLiterals name="Discrete" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="StochasticityEffectType">
    <eLiterals name="Probabilistic"/>
    <eLiterals name="NonDeterministic" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Pattern">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="patternType" eType="#//PatternType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UncertaintyPerspective">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="perspective" eType="#//UncertaintyPerspectiveType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="specification" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UncertaintySource">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="source" eType="#//UncertaintySourceType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="specification" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="PatternType">
    <eLiterals name="Periodic"/>
    <eLiterals name="Persistent" value="1"/>
    <eLiterals name="Sporadic" value="2"/>
    <eLiterals name="Transient" value="3"/>
    <eLiterals name="Random" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="UncertaintyPerspectiveType">
    <eLiterals name="Subjective"/>
    <eLiterals name="Objective" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="UncertaintySourceType">
    <eLiterals name="MODEL"/>
    <eLiterals name="NOISE_IN_SENSING" value="1"/>
    <eLiterals name="RESOURCES" value="3"/>
    <eLiterals name="GOAL_OBJECTIVES" value="4"/>
    <eLiterals name="ENVIRONMENT" value="5"/>
    <eLiterals name="HUMAN_IN_THE_LOOP" value="6"/>
    <eLiterals name="MANAGED_SYSTEM_UNCERTAINTY" value="7"/>
  </eClassifiers>
</ecore:EPackage>
