<?xml version="1.0" encoding="UTF-8"?>

<project xmlns="http://maven.apache.org/POM/4.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>tools.vitruv</groupId>
    <artifactId>tools.vitruv.casestudies.brakesystem</artifactId>
    <version>0.1.0-SNAPSHOT</version>
  </parent>

  <artifactId>tools.vitruv.casestudies.brakesystem.viewtype</artifactId>

  <name>Viewtype</name>
  <description />


  <dependencies>
    <!-- project dependencies-->
    <dependency>
      <groupId>${project.groupId}</groupId>
      <artifactId>tools.vitruv.casestudies.brakesystem.model</artifactId>
      <version>${project.version}</version>
    </dependency>

    <!-- Vitruvius dependencies -->
    <dependency>
      <groupId>tools.vitruv</groupId>
      <artifactId>tools.vitruv.change.atomic</artifactId>
    </dependency>
    <dependency>
      <groupId>tools.vitruv</groupId>
      <artifactId>tools.vitruv.change.composite</artifactId>
    </dependency>
    <dependency>
      <groupId>tools.vitruv</groupId>
      <artifactId>tools.vitruv.framework.views</artifactId>
    </dependency>

    <!-- Thesis dependencies -->
    <dependency>
      <groupId>tools.vitruv.compmodelcons</groupId>
      <artifactId>tools.vitruv.compmodelcons.views</artifactId>
      <version>0.1.0-SNAPSHOT</version>
    </dependency>
    <dependency>
      <groupId>tools.vitruv.compmodelcons</groupId>
      <artifactId>tools.vitruv.compmodelcons.change</artifactId>
      <version>0.1.0-SNAPSHOT</version>
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>build-helper-maven-plugin</artifactId>
        <executions>
          <execution>
            <id>add-source-neojoin</id>
            <phase>generate-sources</phase>
            <goals>
              <goal>add-source</goal>
            </goals>
            <configuration>
              <sources>
                <source>${project.basedir}/src/main/neojoin</source>
                <source>${project.build.directory}/generated-sources/neojoin</source>
              </sources>
            </configuration>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>org.eclipse.xtext</groupId>
        <artifactId>xtext-maven-plugin</artifactId>
        <configuration>
          <projectMappings>
            <projectMapping>
              <projectName>${project.artifactId}</projectName>
              <path>${project.basedir}</path>
            </projectMapping>
          </projectMappings>
          <languages>
            <language>
              <setup>tools.vitruv.compmodelcons.generator.NeoJoinVitruvBuildSetup</setup>
              <outputConfigurations>
                <outputConfiguration>
                  <outputDirectory>
                    ${project.build.directory}/generated-sources/neojoin
                  </outputDirectory>
                </outputConfiguration>
              </outputConfigurations>
            </language>
          </languages>
        </configuration>
        <dependencies>
          <dependency>
            <groupId>tools.vitruv.compmodelcons</groupId>
            <artifactId>tools.vitruv.compmodelcons.generator</artifactId>
            <version>0.1.0-SNAPSHOT</version>
          </dependency>
          <dependency>
            <groupId>tools.vitruv.compmodelcons</groupId>
            <artifactId>tools.vitruv.compmodelcons.views</artifactId>
            <version>0.1.0-SNAPSHOT</version>
          </dependency>
          <dependency>
            <groupId>tools.vitruv.compmodelcons</groupId>
            <artifactId>tools.vitruv.compmodelcons.change</artifactId>
            <version>0.1.0-SNAPSHOT</version>
          </dependency>
          <dependency>
            <groupId>${project.groupId}</groupId>
            <artifactId>tools.vitruv.casestudies.brakesystem.model</artifactId>
            <version>${project.version}</version>
          </dependency>
        </dependencies>
      </plugin>
      <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>exec-maven-plugin</artifactId>
        <executions>
          <execution>
            <id>execute-mwe2-generate</id>
            <phase>generate-sources</phase>
          </execution>
        </executions>
        <dependencies>
          <dependency>
            <groupId>tools.vitruv.compmodelcons</groupId>
            <artifactId>tools.vitruv.compmodelcons.generator</artifactId>
            <version>0.1.0-SNAPSHOT</version>
          </dependency>
        </dependencies>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-antrun-plugin</artifactId>
        <version>3.1.0</version>
        <executions>
          <execution>
            <id>ensure-manifest-exists</id>
            <phase>prepare-package</phase>
            <goals>
              <goal>run</goal>
            </goals>
            <configuration>
              <target>
                <touch
                        file="${project.basedir}/META-INF/MANIFEST.MF"
                        mkdirs="true" />
              </target>
            </configuration>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <artifactId>maven-jar-plugin</artifactId>
        <configuration>
          <archive>
            <manifestFile>${project.basedir}/META-INF/MANIFEST.MF</manifestFile>
          </archive>
        </configuration>
      </plugin>
    </plugins>
  </build>
</project>